### ISSUE TITLE
Зафиксировать версию mistral

### ISSUE THREAD

**Issue by stewkk** [BaldiSlayer/rofl-lab1#129]
+ в апи, кажется, можно передать сид, чтобы ответы были воспроизводимыми

**Comment by ark2016** [comment]
можно фиксировать модель (сейчас используется `mistral-large-2411` == `mistral-large-latest` на сегодняшний день), про сид информации в документации не видел

**Comment by stewkk** [comment]
> можно фиксировать модель (сейчас используется `mistral-large-2411` == `mistral-large-latest` на сегодняшний день), про сид информации в документации не видел

![Screenshot_2024-12-02-16-23-49-486-edit_com.android.chrome.jpg](https://github.com/user-attachments/assets/ed1b4f11-9a37-4f50-8834-bd83130466c7)
