### ISSUE TITLE
Исследование галлюцинаций

### ISSUE THREAD

**Issue by ark2016** [BaldiSlayer/rofl-lab1#20]
Оставляйте найденные галлюцинации в [формате из предыдущего issue](https://github.com/BaldiSlayer/rofl-lab1/issues/7) в комментарии ниже (потом всё объединим и сохраним за раз, БД дорабатывается)
```
[
  {
    "question": "Что такое ТФЯ?",
    "answer": "теория формальных языков",
  },
  {
     "question": "Что такое ДКА?",
     "answer": "детерминированный конечный автомат",
  },
]
```
Запрос делаете из `LLM/Mistral/mistral.py` добавляя API-ключ предварительно в `LLM/Mistral/getAPIkey.py` (если до #19 делаете, если после, то ключ добавляете в `LLM/Mistral/mistral.py`)
использование функции `get_chat_response` как в примере ниже 
```py
prompt = "вопрос"
context = "контекст"
response = get_chat_response(prompt, context)
print(response) # вывод ответа
```

**Comment by stewkk** [comment]
> upd: сохраняем в формате JSON в `data/data.json` в ветке `data`

Предлагаю эту ветку помержить, а данные вносить в отдельных ПР

**Comment by ark2016** [comment]
> > upd: сохраняем в формате JSON в `data/data.json` в ветке `data`
> 
> Предлагаю эту ветку помержить, а данные вносить в отдельных ПР

Думаю будет слишком много PR, проще всё в 1 ветке, а потом её слить, чтобы часто в мейн не пушить

**Comment by stewkk** [comment]
> > > upd: сохраняем в формате JSON в `data/data.json` в ветке `data`
> > 
> > 
> > Предлагаю эту ветку помержить, а данные вносить в отдельных ПР
> 
> Думаю будет слишком много PR, проще всё в 1 ветке, а потом её слить, чтобы часто в мейн не пушить

Ну, часто пушить в мейн правильнее =)
+ так преподавателю проще оценивать, кмк

**Comment by BaldiSlayer** [comment]
полностью согласен с Сашей, только надо попросить всех ветки удалять после мерджа, чтобы не плодились, а так - кажется, что частый мердж это вполне себе ок)

**Comment by stewkk** [comment]
> полностью согласен с Сашей, только надо попросить всех ветки удалять после мерджа, чтобы не плодились, а так - кажется, что частый мердж это вполне себе ок)

[github flow](https://docs.github.com/en/get-started/using-github/github-flow) =)))

**Comment by stewkk** [comment]
Это, кажется, не используется. Прикрою
