### ISSUE TITLE
Поправить замечания по ревью телеграм бота

### ISSUE THREAD

**Issue by stewkk** [BaldiSlayer/rofl-lab1#73]
#68 

+ поправить излишнее экранирование во всех шаблонах сообщений
+ предвыделить память под строковое представление TRS
+ [лишний else](https://github.com/BaldiSlayer/rofl-lab1/pull/68#discussion_r1834227626)
+ обернуть ошибки
+ возвращать не более двух значений (сделать структурки)
+ defer f.Close()
+ ExitOnError()

**Comment by TonitaN** [comment]
@stewkk , ещё ряд предложений:
- сделать режим рабочий, в котором выводится только один (основной) ответ, для теста скорости. Основным пока оставить тестовый, с логами и тремя вариантами (пока работаем с БЗ, он идеален для этой цели). Посмотреть по таймаутам, и если модель в среднем думает больше, чем 30 секунд, добавлять пояснение, что ответ готовится.
- аналогично с formalize - неплохо бы предупреждать пользователя о том, что происходит (формализация, передача в интерпретатор, проверка модели в smt-решателе).
