### ISSUE TITLE
Добавить шаблонизированный промпт для запросов в БЗ

### ISSUE THREAD

**Issue by stewkk** [BaldiSlayer/rofl-lab1#91]
Хотим посмотреть, как влияет настройка промпта на качество ответов БЗ. Пример промпта от @BaldiSlayer тут:

https://github.com/BaldiSlayer/rofl-lab1/issues/55#issuecomment-2455308305

**Comment by BaldiSlayer** [comment]
как минимум добавление промта возьму на себя, как некст таску
